#!/bin/sh

#/usr/bin/invoke_app "$@" -C "start_jupyter -T @tool Index.ipynb" \
/usr/bin/invoke_app "$@" -C "start_jupyter -T @tool manual/manual.ipynb" \
                         -u anaconda-6 \
                         -r none \
                         -e LD_LIBRARY_PATH=@tool/lib:${LD_LIBRARY_PATH}

